import { Inter } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/app/theme'
import { getServerSession } from "next-auth";
import AuthProvider from "@/contexts/sessionProvider";

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { CssBaseline } from "@mui/material";
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

import { ApolloContext } from "@/contexts/apolloContext";

const inter = Inter({ subsets: ["latin"] });

// APollo client / GRAPHQL can only be used in client component

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


if (true) {  // Adds messages only in a dev environment
  loadDevMessages();
  loadErrorMessages();
}

export default async function RootLayout({ children }) {

  const session = await getServerSession();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <AuthProvider session={session}>
            <AppRouterCacheProvider>
                <ThemeProvider theme={theme}>
                  <CssBaseline />
                  <ApolloContext>
                      {children}
                  </ApolloContext>
                </ThemeProvider>
            </AppRouterCacheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}