import { Inter } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '@/app/theme'
import { getServerSession } from "next-auth";
import AuthProvider from "@/contexts/sessionProvider";


import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
      <AuthProvider session={session}>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
        <CssBaseline />
          {children}
        </ThemeProvider>
      </AppRouterCacheProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
